### ISSUE TITLE
matcher 'be_an_existing_file' returns false

### ISSUE THREAD

**Issue by donnerluetjen** [cucumber/aruba#310] opened 2015-10-11 11:47 UTC
Hi there,
I can't figure out why the matcher is not working as expected. Is this a bug?

I've created a [sample project](https://github.com/donnerluetjen/aruba_sample.git) that shows the behavior and lists my environment (aruba 0.9.0).
I am creating a file via touch
`touch #{file}`.
I can verify that the file exists.
But when I use
`expect(file).to be_an_existing_file` the expectation fails. 

Am I doing something wrong here?

Thank you for your time.

**Comment by dg-ratiodata** [comment] 2015-10-12 15:31
Hi @donnerluetjen,

thanks very much for the sample project. I think the problem is this:

`aruba` expects you to create the file in its working directory which normally is `<project_root>/tmp/aruba`. Since you create the file in `<project_root>`, the check fails because `<project_root>/tmp/aruba/your-file.txt` does not exist.

To solve your problem try one of the following:

1. Change the configuration setting for the working directory [doc](https://github.com/cucumber/aruba/blob/master/features/configuration/working_directory.feature#L23)
2. You the steps of aruba
  ~~~cucumber
  Given an empty file named "blub.txt"
   Then a file named "blub.txt" should exist
  ~~~
3. If you don't want to use cucumber and want to use rspec instead have a look at this [documentation](https://github.com/cucumber/aruba/blob/master/features/api/filesystem/create_directory.feature). Unfortunately I need to find some time to finish the rest of the documentation

Does this help you with your problem?

**Comment by dg-ratiodata** [comment] 2015-10-12 15:35
I'am going to close this for now. Please let me know if this helped you. :-)

**Closed by dg-ratiodata** 2015-10-12 15:35 UTC
