### ISSUE TITLE
Content of environment variable set by another ruby library gets lost

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#405] opened 2016-06-05 12:09 UTC
## Summary

The [middleman/middleman] project supports "stylus"-templates. This is a javascript library which is bundled into a ruby gem. The gem modifies the content of some nodejs environment variables which are required to be modified so that, "stylus" get be found.

## Expected Behavior

The "stylus"-gem should work with aruba.

## Current Behavior

The content of the environment variables gets lost because of aruba's isolation mechanism for environment variables.

```
```
## Possible Solution

Fix the isolation mechanism

## Steps to Reproduce (for bugs)

Try to migrate "middleman" to new version of aruba. Some tests will fail. See https://github.com/maxmeyer/middleman/commits/feature/upgrade-aruba-012 for this.
## Your Environment

- Version used: latest
- Operating System and version:
- Link to your project: https://github.com/maxmeyer/middleman/commits/feature/upgrade-aruba-012

**Comment by maxmeyer** [comment] 2017-07-31 05:42
This might be fixed by #442

**Comment by mvz** [comment] 2017-11-08 10:19
I can't reproduce this with the branch given. @maxmeyer can you?

There are commits in 0.12.0 that seem to address this (specifically: bc0f98be6d68f7ef6119a5a0f6849601b58d5faa), which is confusing since this bug applies to 0.12.0.

**Comment by maxmeyer** [comment] 2017-11-13 22:12
I'm really sorry, but I don't have time to dig into code.

**Comment by mvz** [comment] 2017-11-14 09:24
Ok, I'll look into this one then.

**Comment by mvz** [comment] 2019-05-20 18:01
This may very well be related to #608.

**Comment by mvz** [comment] 2019-06-16 10:13
Closing for now as no longer reproducible.

**Closed by mvz** 2019-06-16 10:13 UTC
Labels: bug, difficulty: hard, status: needs review
